bot-directories=C:\\Users\\Wicus\\Documents\\GitHub\\Four04FoundUs\\sample-bots-csharp-0.33.1,true,C:\\Users\\Wicus\\Documents\\GitHub\\Four04FoundUs\\sample-bots-csharp-0.33.1\\Four04FoundUs,true,C:\\Users\\ferre\\OneDrive\\Desktop\\Hackathon_EPS\\Four04FoundUs\\sample-bots-csharp-0.33.1,true
game-type=classic
tps=500
